language: java
jdk:
  - oraclejdk8

before_install:
  - pip install --user codecov
after_success:
  - bash <(curl -s https://codecov.io/bash) -t :zQjCSZzyUk

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/